version: "3.4"
services:
    selenium:
        image: "elgalu/selenium"
    zalenium:
        image: "dosel/zalenium"
        container_name: "zalenium"
        privileged: true
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/videos:/home/seluser/videos
        ports:
            - "4444:4444"
        command: >
            start --desiredContainers 2
                  --maxDockerSeleniumContainers 2
                  --screenWidth 800
                  --screenHeight 600
                  --videoRecordingEnabled true
